project/Build.scala

(Eclipse complains about incompatible scala version otherwise.)

Fixed discrepancy on scalatest between pom and sbt build systems.

---

src/main/scala/cc/factorie/app/topics/lda/LDA.scala

Should fix "Errors in multi-threaded LDA and with SparseOnlineLDA in factorie_2.11-1.2-SNAPSHOT" from mailing list.

fix LDA bug

---

pom.xml
src/main/scala/cc/factorie/util/JsonCubbieConverter.scala
src/test/scala/cc/factorie/app/nlp/TestDocumentStore.scala
src/test/scala/cc/factorie/util/TestJsonCubbieConverter.scala

Currently should support the same set of objects that MongoCubbieConverter does (ie. no Tensors).

Basic code to read and write cubbies to JSON

---

src/main/scala/cc/factorie/app/nlp/load/Load.scala
src/main/scala/cc/factorie/app/nlp/load/LoadConll2002.scala
src/main/scala/cc/factorie/app/nlp/load/LoadConll2008.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala
src/main/scala/cc/factorie/app/nlp/pos/ChainPosTagger.scala
src/main/scala/cc/factorie/app/nlp/pos/PosTag.scala

Pos and ner tagging for Spanish. Previously pull requested to tackbp-2015 branch.

Spanish ner pos

---

src/main/scala/cc/factorie/app/nlp/Sentence.scala
src/main/scala/cc/factorie/app/nlp/Token.scala
src/main/scala/cc/factorie/app/nlp/coref/DeterministicCoref.scala
src/main/scala/cc/factorie/app/nlp/coref/MentionPhraseFinder.scala
src/main/scala/cc/factorie/app/nlp/phrase/DatePhraseFinder.scala
src/main/scala/cc/factorie/app/nlp/phrase/Phrase.scala

Changed many instances of token.postag to token.attr[PennPosTag]

change Token.posTag to return abstract PosTag rather than PennPosTag. 

---

src/main/scala/cc/factorie/app/nlp/NLP.scala

--token will just tokenize, and --token-norm will both tokenize and normalize. This resolves Issue #283.

Add option to tokenize with/without normalization to command line tool

---

src/main/scala/cc/factorie/util/Cubbie.scala
src/main/scala/cc/factorie/util/JsonCubbieConverter.scala

Special handling of empty IntSeq and DoubleSeq objects in JSON serialization and deserialization of cubbies.

JSON/Cubbie Serialization & Deserialization, handling empty lists

---

src/main/scala/cc/factorie/util/namejuggler/PersonNameParser.scala

1. Handling edge case where name string is ","
2. Added parseFullNameSafe which returns None in the case where parseFullName would throw an exception for invalid/empty name strings.

Small changes to Person name parser

---

src/main/scala/cc/factorie/app/nlp/segment/EnglishLexer.flex

Specifically, matching tags of the format <some-tag some-field-name="some quotation">.

Added a regex to match more SGML tags 

---

sbt

sbt script was broken, now it is fixed

Update sbt script to reflect new typesafe repo

---

src/main/scala/cc/factorie/app/nlp/embedding/SkipGram.scala
src/main/scala/cc/factorie/app/nlp/embedding/WindowWordEmbedder.scala

Added my implementation of skipgram to the existing embedding code. Changed the WindowWordEmbedder vocabulary code to actually write out vocab as intended.

Skipgram code in nlp/embedding

---

project/Build.scala

Things:
- use json4s-jackson
- seq is deprecated and leads to issues with SBT (~ 0.13.7)

Fixes issues with SBT build

---

src/main/scala/cc/factorie/app/chain/LiteChainModel.scala

A more flexible and slightly less efficient version of ChainModel to make things like sparse edge features work.

Add LiteChainModel for sparse edge features, label embeddings, etc

---

src/main/scala/cc/factorie/app/nlp/ner/ChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/NERChunkAnnotator.scala

Also removed two implicit args from OntonotesChainNer to make it match ConllChainNer.

Lost two lines from NERChunkAnnotator in a merge, this replaces them.

---

src/main/scala/cc/factorie/app/nlp/NLP.scala
src/main/scala/cc/factorie/app/nlp/ner/ChainNer.scala

also some very minimal cleanup in ConllChainNer

Fix calling StackedChainNer from command line tool

---

project/Build.scala

…so that both build tools work with bin/fac script

Fix Build.sbt to produce packaged jar with same name as mvn package

---

.travis.yml
src/main/scala/cc/factorie/app/nlp/Section.scala
src/main/scala/cc/factorie/app/nlp/load/LoadConll2002.scala
src/main/scala/cc/factorie/app/nlp/load/LoadConll2003.scala

Also add += and -= on Section, and remove a bunch of commented stuff in LoadCoNLL2002

Fix CoNLL2003 loader to not load empty sentences

---

src/main/scala/cc/factorie/app/nlp/parse/ParseTree.scala

Remove unnecessary import in ParseTree

---

src/main/scala/cc/factorie/app/chain/ChainModel.scala

I changed the for-loops to while-loops in maximize and getMaximizedLabels.

Change some for-loops to while-loops in ChainModel

---

src/main/scala/cc/factorie/app/nlp/embeddings/SkipGramEmbedding.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala

Also don't hardcode skipgramembedding file location

ConllStackedChainNerTrainer compatible with embeddings

---

src/main/scala/cc/factorie/tutorial/UsersGuide420Factors.scala

- s2 is the statistics of (77, 8.8)
- s2c is the current statistics, which is still (1, 4.4)

A small typo in a variable name in the tutorial

---

bin/fac

Closes factorie/factorie#363.
I have updated `bin/fac` to automatically retrive the factorie version from `pom.xml`

Automatic retrival of factorie version in bin/fac

---

src/main/scala/cc/factorie/app/nlp/load/TacFileIterator.scala
src/main/scala/cc/factorie/app/nlp/load/XMLSectionalizer.scala

Revert back to old XML Sectionalizer that removes sgml tags. Add Broadcast sectionalizer

Revert back to old XML Sectionalizer that removes sgml tags. Add Broadcast sectionalizer

---

src/main/scala/cc/factorie/app/classify/Classify.scala
src/main/scala/cc/factorie/util/CmdOption.scala

https://groups.google.com/a/factorie.cs.umass.edu/forum/#!topic/discuss/qFnuIboMluk
Fix for --help which currently only prints explanations without commands

Fix for --write-classifications see this thread:

---

src/main/scala/cc/factorie/app/topics/lda/Document.scala

See this thread,
https://groups.google.com/a/factorie.cs.umass.edu/forum/#!topic/discuss/XsBNCb4uIKY

Close file after use
