factorie/factorie

src/main/scala/cc/factorie/app/nlp/phrase/NounPhraseEntityType.scala
src/main/scala/cc/factorie/tutorial/ChainNERDemo.scala
src/main/scala/cc/factorie/variable/CategoricalSeqVariable.scala
src/main/scala/cc/factorie/variable/CategoricalVectorVariable.scala

This is the most common desired behavior, so it should be the default. If the domain is never frozen then this behavior is the same as the old behavior. Also, the old default (false) tends to cause ArrayIndexOutOfBounds exceptions when trying to predict on real data (when, as is often the case, features get computed that are outside the domain).
This PR also includes some changes to ChainNERDemo that demonstrate this common use case of first computing features on training data, then freezing the feature domain before computing test feats.

Change default value of skipNonCategories to domain.dimensionDomain.frozen

---

src/main/scala/cc/factorie/app/nlp/parse/ParseTree.scala

To allow for building a tree from a list of dependencies that doesn't necessarily cover every token in the sentence.

Some fixes to ParseTree

---

src/main/scala/cc/factorie/app/nlp/coref/MentionPhraseFinder.scala
src/main/scala/cc/factorie/app/nlp/segment/DeterministicLexerTokenizer.scala
src/main/scala/cc/factorie/app/nlp/segment/EnglishLexer.flex
src/test/scala/cc/factorie/app/nlp/segment/TestLexerTokenizer.scala

- Fix the tokenizer so that "euro" does not get tokenized/normalized to "eur o" / "$ o"
- Add PennPosTag as a prerequisite for ConllProperNounPhraseFinder, since it is

Small fix to tokenizer, ConllProperNounPhraseFinder

---

src/main/scala/cc/factorie/app/nlp/ner/NerTag.scala
src/main/scala/cc/factorie/app/nlp/ner/OntonotesChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala
src/test/scala/cc/factorie/app/nlp/ner/TestNerTag.scala

When BasicOntonotesNER.process is run the document attr OntonotesNerSpanBuffer is always empty because of a bug in how that class is defined.  This pull request provides a simple fix to the class definition of OntonotesNerSpanBuffer that is modeled directly on how a similar class, ConllNerSpanBuffer, in the same source file (NerTag.scala) is implemented.  I have included a simple test that illustrates the problem.  The line that is commented in that test will compile and create a test failure without the provided changes to src/main/scala.  As it is, it illustrates that the code works correctly with the bug fix.  I have also tested this separately on an end-to-end run of an NER annotator and verified that the contents of OntonotesNerSpanBuffer are correct.  This contribution is covered by …

Fix OntonotesNerSpanBuffer so that it is populated after NER is run

---

.gitignore
src/main/scala/cc/factorie/maths/package.scala

According to the docs the Java Random implementation is the same as ours (Box-Muller): http://docs.oracle.com/javase/7/docs/api/java/util/Random.html#nextGaussian()
Except it is threadsafe. Also remove long-deprecated and commented method from maths package, and add sbt .history to .gitignore.

Use Java nextGaussian to get Gaussian random numbers

---

README.md

classify argument `--read-text-dirs` expects dirs to be separated by "," as could be seen in `cc.factorie.app.classify.Classify`:
`for (directory <- opts.readTextDirs.value.split(",")) {`
moreover; there should be no space; since `readTextDirs.value` contains only the first token.

fix of example of using classify --read-text-dirs

---

src/main/scala/cc/factorie/app/classify/Classify.scala

Added an option for specifying a root directory so that its subdirectories could become labels (equivalent for listing all of them on the command line).
This is similar to mallet's [import-dir](http://mallet.cs.umass.edu/import.php).  This is a convenience feature, particularly applicable when the number of labels is large.

read-text-dirs: add option for reading labels from subdirectories

---

src/main/scala/cc/factorie/la/SparseIndexedTensor.scala

This should resolve issue #131, which still had a bug in the case where both vectors had the same number of non-zero values.

Fix to dot on ArraySparseIndexedTensor (see issue #131)

---

src/main/scala/cc/factorie/app/nlp/embedding/CBOW.scala

I removed this line to try to resolve the "build failing" report from Travis. 
It seems this line is not needed after the refactoring of the embedding code?

Removing line, which caused compilation problem. It does not seem to be necessary after refactoring?

---

src/main/scala/cc/factorie/variable/CategoricalDomain.scala
src/test/scala/cc/factorie/variable/TestCategoricalDomain.scala

make behavior of += and ++= consistent in CategoricalDomain

---

.travis.yml
src/main/scala/cc/factorie/util/HyperparameterSearcher.scala

Add mem_free flag in addition to mem_token flag to both 1) tell grid that we're using the memory and 2) ensure that the memory is available, because for some reason these are separate things.

Fix memory allocation in qsub utils (hyperparam optimizer)

---

pom.xml
project/Build.scala

From 2.11.2 to 2.11.7, this is PR #309 (sbt) plus updates to pom for Maven.

Bump Scala version

---

src/main/scala/cc/factorie/app/chain/Observation.scala
src/main/scala/cc/factorie/app/nlp/ner/OntonotesChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala
src/main/scala/cc/factorie/variable/ChainVariable.scala

This pull request is a few patches that Kate and I worked on over the summer to improve the runtime performance of StackedChainNER. Under profiling it bumps the speed by about 2x, without profiling it takes a test run on a single document (after warmup) from ~45s to ~12s (about 3x speedup). The regex changes make the standard ChainNER more efficient, but it doesn't seem to improve the speed of that model.
There are three groups of changes: 
-- refactoring the addNeighboringFeatureConjunctions method to take a precompiled regex rather that recompiling the same regex for each token in each document. There are stub methods for the old signatures which convert the arguments appropriately.
-- refactoring initSecondaryFeatures so it uses a hashmap rather than repeatedly counting a linked list, …

Ner performance improvements

---

src/main/scala/cc/factorie/app/nlp/Document.scala
src/main/scala/cc/factorie/app/nlp/Sentence.scala
src/main/scala/cc/factorie/app/nlp/Token.scala
src/main/scala/cc/factorie/app/nlp/TokenSpan.scala
src/main/scala/cc/factorie/app/nlp/ner/ChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/NerTag.scala
src/main/scala/cc/factorie/app/nlp/ner/OntonotesChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala
src/main/scala/cc/factorie/app/nlp/pos/ChainPosTagger.scala
src/main/scala/cc/factorie/app/nlp/pos/ForwardPosTagger.scala
src/main/scala/cc/factorie/app/nlp/pos/PosTag.scala
src/main/scala/cc/factorie/util/Attr.scala

This pull request adds java serialization tags to the classes involved in NER tagging. It also contains custom serialization and deserialization methods for the Attr trait, as we found a bug in Scala's serialization implementation with inner objects (see https://issues.scala-lang.org/browse/SI-9375). Hopefully this will be patched in Scala 2.11.8 and then the extra methods can be removed.
This is some of the work Kate did over the summer. There will be another pull request relating to NER performance improvements she worked on once I've extracted it from our source tree.

Java serialization for the NER stack

---

src/main/scala/cc/factorie/app/nlp/lexicon/AhoCorasick.scala
src/main/scala/cc/factorie/app/nlp/lexicon/TrieNode.scala

These are two small bugfixes to the AhoCorasick implementation. 
The first commit fixes an issue where findMentions would occasionally hit an ArrayIndexOutOfBoundsException due to the sentinel value sometimes escaping into the outputSet. The second & third commit fixes the readObject method on AhoCorasick as Scala methods interact oddly with the JVM's serialization infrastructure.

Lexicon bugfixes

---

src/main/scala/cc/factorie/app/classify/backend/NaiveBayes.scala
src/test/scala/cc/factorie/app/classify/backend/TestNaiveBayes.scala

This PR addresses two issues regarding the Naive Bayes implementation:
- The learned weights should be indexed as (Features x Labels).
- Some inconsistencies in the test were fixed.

Fixed naive bayes indexing and test.

---

src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala

The StackedChainNER has two feature domains, the first of which is properly frozen before the test documents' features are generated. The second domain has the features generated for both train and test documents at the same time, thus adding all the (unseen) test time features to the second domain. The model parameters for these features are all zero as they don't appear in the training set (about 6 million zeros for the Ontonotes dataset using one random split).
These zeros are part of the stored model file, which results in the OntonotesStackedChainNER model file being approx 657MB, instead of approx 598MB after this patch. The in memory representation of the StackedChainNER model decreases by the same amount.

StackedChainNER adds the test features before freezing the second domain

---

src/main/scala/cc/factorie/app/chain/ChainModel.scala
src/main/scala/cc/factorie/app/nlp/DocumentAnnotatorPipeline.scala
src/main/scala/cc/factorie/app/nlp/ner/ChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/NERChunkAnnotator.scala
src/main/scala/cc/factorie/app/nlp/ner/NerTag.scala
src/main/scala/cc/factorie/app/nlp/ner/WellFormedNer.scala

The meat here is `cc.factorie.app.nlp.ner.WellFormedNer` which takes a `ChainNer` (it is easily adaptable to `StackedChainNer`) and processes a document by annotating it exactly as it's instance of `ChainNer` would, except that it only permits licit transitions as defined by the label domain (see `cc.factorie.app.nlp.ner.SpanEncoding`).
This exists primarily to make things easy for `cc.factorie.app.nlp.ner.NerChunkAnnotator`, and should, in general, process a document before it.

Added a document processor to ensure that ner tags are well-formed.

---

src/main/scala/cc/factorie/util/DoubleSeq.scala
src/test/scala/cc/factorie/util/TestDoubleSeq.scala

This fixes a bug with SparseDoubleSeq.sampleIndex. Since only active elements are iterated, the last index needs to be carried with the sweep. Note that SparseDoubleSeq is tested via the cc.factorie.la.SparseTensor1 implementation.

Fix sampleindex for SparseDoubleSeq

---

src/main/scala/cc/factorie/variable/ChainVariable.scala

This fixes the issue where prevWindow(0) called on the first element in a ChainLink would return the first element, and where prevWindow(i>0)/nextWindow(i>0) would return the first/last element when called on the first/last element respectively.

Fix bug in prevWindow/nextWindow

---

src/main/scala/cc/factorie/app/nlp/NLP.scala
src/main/scala/cc/factorie/app/nlp/lemma/LowercaseLemmatizer.scala
src/main/scala/cc/factorie/app/nlp/ner/ChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/NerLexiconFeatures.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/StaticLexiconFeatures.scala
src/main/scala/cc/factorie/app/strings/StringSegmenter.scala

This pull request adds a trait that abstracts out the lexicon-based features found in ChainNer and StackedChainNer.  The trait is called NerLexiconFeatures.
- provides default implementation, StaticLexiconFeatures, using existing
code taken from ChainNer.addFeatures and StackedChainNer.initFeatures
- ChainNer and StackedChainNer and various class/object definitions that instantiate it now use StaticLexiconFeatures
This removes redundant code, but more importantly for my purposes is that it allows me to experiment with a completely different approach to handling the lexicon-based features.
I also snuck in a couple of misc. edits to the following classes so that my experiments run correctly.
StringSegmenter.RegexSegmenter is serializable
LowercaseLemmatizer is serializable

Add trait NerLexiconFeatures for isolating lexicon-based features in NER

---

pom.xml
project/Build.scala
src/main/scala/cc/factorie/util/Attr.scala
src/main/scala/cc/factorie/util/JsonCubbieConverter.scala

This bumps the Scala version to 2.11.8, and removes the workaround we patched in to the java.io.Serialization of Attr objects.
It's not actually listed as being a bug fixed in Scala 2.11.8 due to a JIRA oddity, but the backport commit for it is https://github.com/scala/scala/pull/4757 and I've verified the fix is in the binary from scala-lang.org.

Bumping Scala version to 2.11.8 to fix SI-9375

---

src/main/scala/cc/factorie/la/Tensor2.scala
src/main/scala/cc/factorie/la/Tensor3.scala
src/main/scala/cc/factorie/la/Tensor4.scala

This commit adds bounds checking to the base multidimensional Tensor classes (i.e. Tensor2, Tensor3, Tensor4). It closes issue #359. All the unit tests pass, and it catches our issue where we'd transposed the indices.
All Tensor accesses through apply, update or += are now routed through singleIndex to calculate the index into the 1d backing array, and that method throws IndexOutOfBoundsException if the indices are negative or beyond the bounds of the array.

Adding bounds checks to Tensor{2,3,4}

---

pom.xml
project/Build.scala

Fixes - File name too long when compiling. This can happen on encrypted or legacy file systems.  Please see SI-3623 for more details.
Removes - the following Maven build warnings
[WARNING] 'artifactId' contains an expression but should be a constant. @ cc.factorie:factorie_${scala.majorVersion}:1.3-SNAPSHOT, /home/sullija/java/workspace/factorie/pom.xml, line 23, column 15
[WARNING] The expression ${pom.groupId} is deprecated. Please use ${project.groupId} instead.

Fixes - File name too long during build.

---

src/main/scala/cc/factorie/app/bib/hcoref/AuthorVars.scala
src/main/scala/cc/factorie/app/nlp/hcoref/DocEntityVars.scala

I believe this is necessary to get single bag templates to unroll properly. Following implementation in external author coref package.

Add noop-diffs to hcoref vars.

---

src/main/scala/cc/factorie/app/nlp/phrase/Phrase.scala

I'm very open to suggestions for better ways to handle this. This PR also does not take care of other methods on the phrase class that use the Penn POS Tag exclusively.

Phrase head token offset change to support pos tags other than penn pos tag.

---

src/main/scala/cc/factorie/app/strings/package.scala
src/test/scala/cc/factorie/app/strings/PackageTest.scala

I found another performance bottle neck in FACTORIE in the cc.factorie.app.strings.simplifyDigits method.  In one configuration, the profiler was showing that 12% of the CPU sampling was taking place in that method executing "findFirstIn".  So, I re-implemented the method using a more direct approach with string/character examination.  Also, I believe the logic of the original implementation is incorrect.  The value returned by simplfiyDigits("A1") is "<NUM>" but I would expect it to be "A#".  I don't think it is possible for the third condition to be invoked based on the way the second one works.  This pull request adds a faster implementation of simplifyDigits and unit tests that capture what I think the exptected behavior should be.  The unit tests do not pass with the regex version of …

reimplemented simplifyStrings for speed and correct behavior

---

pom.xml
src/main/scala/cc/factorie/app/nlp/ner/ChainNer.scala
src/main/scala/cc/factorie/app/nlp/ner/StackedChainNer.scala

scala upgraded to 2.11.11
add the missing ClassTag in NER annotators

patch for object ConllChainNer creation failure #385
